version: "2"

services:
  baemon-sim:
    platform: linux/amd64
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=db
      - DB_USERNAME=syahbudin
      - DB_DATABASE=syahbudin
      - DB_PASSWORD=syahbudin
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: php artisan serve --host=0.0.0.0 --port=3000

  db:
    platform: linux/amd64
    image: mysql:8
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: syahbudin
      MYSQL_DATABASE: syahbudin
      MYSQL_USER: syahbudin
      MYSQL_PASSWORD: syahbudin
    cap_add:
      - SYS_NICE

  pma:
    platform: linux/amd64
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: syahbudin
      PMA_PASSWORD: syahbudin
      MYSQL_ROOT_PASSWORD: syahbudin
